version: '3.9'
services:
  curso.dapper.api:
    container_name: oracle-xe-curso-dapper
    image: gvenzl/oracle-xe:21-slim

    ports:
      - "1521:1521"        # Porta do Oracle
      - "5500:5500"        # Porta do Enterprise Manager (opcional)
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=appuser
      - APP_USER_PASSWORD=app123

    volumes:
      - ./oracle-data:/opt/oracle/oradata   # persistÃªncia dos dados
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/oracle@//localhost:1521/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
